# PDFをpdftocairoでPNG化後、gimpで白背景を選択透明化
from graphviz import Digraph
import os

G = Digraph(format='svg')
G.attr(compound='true', fontname='A-OTF UD Shin Maru Go Pr6N', rankdir='LR')

# 外部ツール
G.attr('node', shape='box', fontname='A-OTF UD Shin Maru Go Pr6N')
G.node('vivliocli', 'Vivliostyle-CLI CSS組版')
G.node('vivliocss', 'Vivliostyle.js CSS組版')
G.node('versacss', 'VersaType Converter CSS組版')
G.node('ahcss', 'Antenna House Formatter CSS組版')
G.node('kindlegen', 'Kindle Previewer')
G.node('indesign', 'InDesign XML組版')
G.node('latex', 'LaTeX (upLaTeX/LuaLaTeX)')
G.node('pandoc2review', 'pandoc2review')
G.node('md2review', 'md2review')
G.node('rvbuilder', 'Sphinx ReVIEW builder')
#G.node('rst', 'review-comple --target=rstbuilder')
G.node('gnuplot', 'Gnuplot')
G.node('graphviz', 'Graphviz')
G.node('blockdiag', 'Blockdiag')
G.node('aafigure', 'aafigure')
G.node('plantuml', 'PlantUML')
G.node('acrobat', 'Acrobat')
G.node('pdftoolbox', 'pdfToolbox')
G.node('pressready', 'press-ready')
G.node('reviewtemplate', 'ReVIEW-Template')

# Re:VIEWコマンド類
G.attr('node', shape='box', style='filled', fillcolor='lightblue2')
G.node('init', '作成(review-init)')
G.node('update', '更新(review-update)')
G.node('preproc', '前処理(review-preproc)')
G.node('vol', '分量確認(review-vol)')
G.node('epub', 'rake epub (review-epubmaker)')
G.node('web', 'rake web (review-webmaker)')
G.node('idgxml', 'rake idgxml (review-idgxmlmaker)')
G.node('pdf', 'rake pdf (review-pdfmaker)')
G.node('epub2html', 'review-epub2html')
G.node('plaintext', 'rake plaintext (review-textmaker -n)')
G.node('text', 'rake text (review-textmaker)')
G.node('vscli', 'rake vivliostyle')

# Re:VIEWプロジェクト、ファイル
with G.subgraph(name='cluster_project') as prj:
    prj.attr(style='filled', fillcolor='gold1', margin='20')
    prj.node_attr.update(shape='note', style='filled', fillcolor='cornsilk')
    #prj.node(['rv'])
    prj.edge_attr.update(style='invis')
    prj.edges([('images', 'images'), ('cssfile', 'cssfile'), ('styfile', 'styfile'), ('yamlfile', 'yamlfile'), ('rv', 'rv')])
    prj.attr(label='Re:VIEWプロジェクト')
    #G.attr('node', shape='ellipse', style='filled', fillcolor='gold1')
    #G.node('project', 'Re:VIEWプロジェクト')

# ファイル
G.attr('node', shape='note', style='filled', fillcolor='cornsilk')
G.node('pdffile', 'PDFファイル')
G.node('epubfile', 'EPUBファイル')
G.node('rv', 'Re:VIEWファイル(.re)')
G.node('images', '画像ファイル')
G.node('word', 'Wordファイル')
G.node('markdown', 'Markdownファイル')
G.node('sphinx', 'Sphinx rstファイル')
G.node('mobi', 'mobiファイル')
G.node('htmlfile', 'HTMLファイル')
G.node('htmlfile2', 'HTMLファイル')
G.node('plaintextfile', '装飾なしテキストファイル')
G.node('textfile', '装飾付きテキストファイル')
G.node('idgxmlfile', 'InDesign XMLファイル')
G.node('latexfile', 'LaTeXファイル')
G.node('cssfile', 'CSSファイル(.css)')
G.node('styfile', 'TeXスタイルファイル(.cls, .sty)')
G.node('yamlfile', '設定YAMLファイル(.yml)')

# 展開先
G.attr('node', shape='cds', style='filled', fillcolor='coral')
G.node('handdtp', '出版社や手動DTPへの提出草稿')
G.node('morph', '形態素解析や文体チェック')
G.node('pdfprint', '印刷製本')
G.node('pdfebook', '電子配布')
G.node('amazon', 'Amazon Kindleストア')
G.node('toritugi', '各電子ブックストア')
G.node('website', 'Webサイト')
#G.node('word', 'Microsoft Word')

G.edge('gnuplot', 'images')
G.edge('graphviz', 'images')
G.edge('blockdiag', 'images')
G.edge('aafigure', 'images')
G.edge('plantuml', 'images')

G.edge('reviewtemplate', 'styfile', lhead='cluster_project')

G.edge('rv', 'epub', ltail='cluster_project')
G.edge('epub', 'epubfile')
G.edge('epubfile', 'versacss')
G.edge('epubfile', 'epub2html')
G.edge('epubfile', 'vscli')
G.edge('vscli', 'vivliocli')
G.edge('epub2html', 'htmlfile2')
G.edge('htmlfile2', 'vivliocss')
G.edge('htmlfile2', 'versacss')
G.edge('htmlfile2', 'ahcss')
#G.edge('epub2html', 'word')
G.edge('vivliocli', 'pdffile')
G.edge('vivliocss', 'pdffile')
G.edge('versacss', 'pdffile')
G.edge('ahcss', 'pdffile')
G.edge('epubfile', 'kindlegen')
G.edge('kindlegen', 'mobi')
G.edge('mobi', 'amazon')
G.edge('epubfile', 'toritugi')

G.edge('pdffile', 'pdfprint')
G.edge('pdffile', 'pdfebook')

G.edge('rv', 'web', ltail='cluster_project')
G.edge('web', 'htmlfile')
G.edge('htmlfile', 'website')

G.edge('rv', 'idgxml', ltail='cluster_project')
G.edge('idgxml', 'idgxmlfile')
G.edge('idgxmlfile', 'indesign')
G.edge('indesign', 'pdffile')

G.edge('rv', 'pdf', ltail='cluster_project')
G.edge('pdf', 'latexfile')
G.edge('latexfile', 'latex')
G.edge('latex', 'pdffile')

G.edge('acrobat', 'pdffile')
G.edge('pdftoolbox', 'pdffile')
G.edge('pressready', 'pdffile')

G.edge('rv', 'plaintext', ltail='cluster_project')
G.edge('rv', 'text', ltail='cluster_project')
G.edge('plaintext', 'plaintextfile')
G.edge('plaintextfile', 'morph')
G.edge('text', 'textfile')
G.edge('textfile', 'handdtp')

G.edge('markdown', 'md2review')
G.edge('md2review', 'rv')

G.edge('word', 'pandoc2review')
G.edge('markdown', 'pandoc2review')
G.edge('pandoc2review', 'rv')

G.edge('sphinx', 'rvbuilder')
G.edge('rvbuilder', 'rv')
#G.edge('rv', 'rst')
#G.edge('rst', 'sphinx')

G.edge('preproc', 'rv')

G.attr('edge', minlen='2')
G.edge('init', 'rv', lhead='cluster_project')
G.edge('update', 'rv', lhead='cluster_project')
G.edge('vol', 'rv', lhead='cluster_project')

G.render('diagram')
